INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2017/05/Kyle-Milliken.jpg','Kyle', 'Milliken','NaN', "Navy","NaN", "Senior Chief Special Warfare Operator (SEAL)", '5/5/2017','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2017/02/SEAL-William-Ryan-Owens.jpg','William', 'Owens','NaN','Navy','NaN','Senior Chief Special Warfare Operator (SEAL)','1/29/2017','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/06/Christian_Pike.jpg','Charles', 'Pike','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','5/3/2016','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/11/Jason-C-Finan.jpg','Jason', 'Finan','NaN','Navy','NaN','Chief Petty Officer (EOD)','10/20/2016','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/07/Nicolas-G-Checque.jpg','Nicolas', 'Checque','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','3/13/2013','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2012/11/kevin-ebbert.jpg','Kevin', 'Ebbert','NaN','Navy','NaN','Special Warfare Operator 1st Class (SEAL)','12/8/2012','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/07/Matthew-G-Kantor.jpg','Matthew', 'Kantor','NaN','Navy','NaN','Special Warfare Operator 1st Class (SEAL)','11/24/2012','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/07/Sean-P-Carson-1.jpg','Sean', 'Carson','NaN','Navy','NaN','Explosive Ordnance Disposal Technician 1st Class (EOD)','8/16/2012','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2012/08/Patrick-Feeks.jpg','Patrick', 'Feeks','NaN','Navy','NaN','Special Warfare Operator 1st Class (SEAL)','8/16/2012','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2012/08/David-Warsen-1.jpg','David', 'Warsen','NaN','Navy','NaN','Senior Chief Special Warfare Operator (SEAL)','8/16/2012','NaN','NaN', true);

INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/07/Christopher-E-Mosko.jpg','Christopher', 'Mosko','NaN','Navy','NaN','Lieutenant (EOD)','4/26/2012','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/07/Caleb-A-Nelson-1.jpg','Caleb', 'Nelson','NaN','Navy','NaN','Special Warfare Operator 1st Class (SEAL)','10/1/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2011/08/Darrick-Benson.jpg','Darrik', 'Benson','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','8/6/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2011/08/Brian-R-Bill.jpg','Brian', 'Bill','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','8/6/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2011/08/Christopher-G-Campbell.jpg','Christopher', 'Campbell','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','8/6/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/07/Jared-W-Day.jpg','Jared', 'Day','NaN','Navy','NaN','Information Systems Technician 1st Class (TECH)','8/6/2011','NaN','NaN', true);

INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2011/08/John-Douangdara.jpg','John', 'Douangdara','NaN','Navy','NaN','Master at Arms 1st Class (TECH)','8/6/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2011/08/John-W-Faas.jpg','John', 'Faas','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','8/6/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2011/08/kevin-houston.jpg','Kevin', 'Houston','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','8/6/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/07/Jonas-B-Kelsall.jpg','Jonas', 'Kelsall','NaN','Navy','NaN','Lieutenant Commander (SEAL)','8/6/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/07/Louis-Langlais.jpg','Louis', 'Langlais','NaN','Navy','NaN','Master Chief Special Warfare Operator (SEAL)','8/6/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2011/08/Mather-D-Mason.jpg','Matthew', 'Mason','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','8/6/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2011/08/Stephen-M-Mills.jpg','Stephen M.','Mills','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','8/6/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2011/08/Nicholas-Null.jpg','Nicholas H.','Null','NaN','Navy','NaN','Chief Explosive Ordnance Disposal Technician (EOD)','8/6/2011','NaN','NaN', true);

INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/07/Jesse-D-Pittman.jpg','Jesse D.','Pittman','NaN','Navy','NaN','Special Warfare Operator 1st Class (SEAL)','8/6/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2011/08/Thomas-A-Ratzlaff.jpg','Thomas A.', 'Ratzlaff0','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','8/6/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2011/08/Robert-J-Reeves.jpg','Robert J.', 'Reeves','NaN','Navy','NaN','Senior Chief Special Warfare Operator (SEAL)','8/6/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2011/08/Heath-Robinson.jpg','Heath M.', 'Robinson','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','8/6/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/07/Nicholas-P-Spehar.jpg','Nicholas P.', 'Spehar','NaN','Navy','NaN','Special Warfare Operator 2nd Class (SEAL)','8/6/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2011/08/Michael-J-Strange.jpg','Michael J. ', 'Strange','NaN','Navy','NaN','Cryptologic Technician Collections 1st Class (TECH)','8/6/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2011/08/Jon-Tumilson.jpg','Jon T.', 'Tumilson','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','8/6/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/07/Aaron-C-Vaughn.jpg','Aaron C.', 'Vaughn','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','8/6/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2011/08/kraig-vickers.jpg','Kraig M. K', 'Vickers','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','8/6/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2011/08/Jason-Workman.jpg','Jason R.', 'Workman','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','8/6/2011','NaN','NaN', true);

INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/07/Brendan-J-Looney.jpg','Brendan J.', 'Looney','NaN','Navy','NaN','Lieutenant (SEAL)','9/21/2010','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2010/09/David-Mclendon.jpg','David B.', 'McLendon','NaN','Navy','NaN','Senior Chief Cryptologic Technician Collections (TECH)','9/21/2010','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/07/Denis-C-Miranda-1.jpg','Denis C.', 'Miranda','NaN','Navy','NaN','Special Warfare Operator 3rd Class (SEAL)','9/21/2010','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2010/09/Adam-O-Smith.jpg','Adam O.', 'Smith','NaN','Navy','NaN','Special Warfare Operator 2nd Class (SEAL)','9/21/2010','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2019/05/Collin-Thomas.jpg','Collin T.', 'Thomas','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','8/18/2010','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/07/Adam-L-Brown-1.jpg','Adam L.', 'Brown','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','3/17/2010','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2009/04/Tyler-Trahan.jpg','Tyler J.', 'Trahan','NaN','Navy','NaN','Explosive Ordnance Disposal Technician 2nd Class (EOD)','4/30/2009','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/07/Jason-R-Freiwald.jpg','Jason R.', 'Freiwald','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','9/11/2008','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2008/09/Marcum.jpg','John W.', 'Marcum','NaN','Navy','NaN','Senior Chief Special Warfare Operator (SEAL)','9/11/2008','NaN','NaN', true);


INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/07/Joshua-T-Harris.jpg','Joshua T.', 'Harris','NaN','Navy','NaN','Special Warfare Operator 1st Class (SEAL)','8/6/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2008/02/Louis-Souffront.jpg','Luis A.', 'Souffront','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','2/7/2008','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/07/Michael-E-Koch.jpg','Michael E.', 'Koch','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','2/4/2008','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/07/Nathan-H-Hardy.jpg','Nathan H.', 'Hardy','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','2/4/2008','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/07/Mark-T-Carter.jpg','Mark T.', 'Carter','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','12/11/2007','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2007/07/STEVEN-P-DAUGHERTY.jpg','Steven P.', 'Daugherty','NaN','Navy','NaN','Cryptologic Technician Technical 1st Class (TECH)','7/6/2007','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2007/07/Jason-D-Lewis.jpg','Jason D.', 'Lewis','NaN','Navy','NaN','Special Warfare Operator 1st Class (SEAL)','7/6/2007','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2007/07/Robert-McRill.jpg','Robert R.', 'McRill','NaN','Navy','NaN','Mass Communications Specialist 1st Class (TECH)','7/6/2007','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2007/04/Joseph-Schwedler.jpg','Joseph C.', 'Schwedler','NaN','Navy','NaN','Special Warfare Operator 2nd Class (SEAL)','4/6/2007','NaN','NaN', true);


INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/08/Michael-Monsoor.jpg','Michael A.', 'Monsoor','NaN','Navy','NaN','Master at Arms 2nd Class (SEAL)','9/29/2006','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2006/08/Marc-A-Lee.jpg','Marc A.', 'Lee','NaN','Navy','NaN','Aviation Ordnanceman 2nd Class (SEAL)','8/2/2006','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2005/06/James-Suh.jpg','James E.', 'Suh','NaN','Navy','NaN','Quartermaster 2nd Class (SEAL)','6/28/2005','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2005/06/shane-patton.jpg','Shane E.', 'Patton','NaN','Navy','NaN','Machinist Mate 2nd Class (SEAL)','6/28/2005','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/06/Daniel-R-Healy.jpg','Daniel R.', 'Healy','NaN','Navy','NaN','Senior Chief Information Systems Technician (SEAL)','6/28/2005','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2005/06/Michael-P-Murphy.jpg','Michael P.', 'Murphy','NaN','Navy','NaN','Lieutenant (SEAL)','6/28/2005','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2005/06/Michael-M-McGreevy.jpg','Michael M.', 'McGreevy, Jr.','NaN','Navy','NaN','Lieutenant (SEAL)','6/28/2005','NaN','NaN', true);


INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2005/06/Jeffrey-Taylor.jpg','Jeffrey S.', 'Taylor','NaN','Navy','NaN','Hospital Corpsman 1st Class (SEAL)','6/28/2005','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2005/06/Lucas.jpg','Jeffrey A.', 'Lucas','NaN','Navy','NaN','Chief Special Warfare Operator (SEAL)','6/28/2005','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/07/Erik-S-Kristensen.jpg', 'Erik S.','Kristensen', 'NaN','Navy','NaN','Lieutenant Commander (SEAL)','8/6/2011','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2005/06/Jacques-J-Fontan.jpg','Jacques J.', 'Fontan','NaN','Navy','NaN','Chief Fire Controlman (SEAL)','6/28/2005','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2016/07/Danny-Dietz.jpg','Danny P.', 'Dietz, Jr.','NaN','Navy','NaN',"Gunner's Mate 2nd Class (SEAL)",'6/28/2005','NaN','NaN', true);


INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2005/06/Matt-Axelson.jpg','Matthew G.', 'Axelson','NaN','Navy','NaN','Sonar Technician Surface 2nd Class (SEAL)','6/28/2005','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2004/05/Brian-J-OUELLETTE.jpg','Brian J.', 'Ouellette','NaN','Navy','NaN',"Boatswain's Mate 1st Class (SEAL)",'5/29/2004','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2003/08/David-Tapper.jpg','David M.', 'Tapper','NaN','Navy','NaN',"Photographer's Mate 1st Class (SEAL)",'8/20/2003','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2003/06/Thomas-Retzer.jpg','Thomas E.', 'Retzer','NaN','Navy','NaN','Internal Communications Specialist 1st Class (SEAL)','6/26/2003','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2002/03/Matthew-J-Bourgeois.jpg','Matthew J.', 'Bourgeois','NaN','Navy','NaN','Chief Hospital Corpsman (SEAL)','3/27/2002','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2002/03/Neil-Roberts.jpg','Neil C.', 'Roberts','NaN','Navy','NaN','Aviation Boatswains Mate 1st Class (SEAL)','3/4/2002','NaN','NaN', true);
INSERT INTO servicemembers (image, first_name, last_name, age, branch_of_service, date_of_birth, unit, date_of_death, awards, summary_of_service, approved) VALUES ('https://www.navysealfoundation.org/wp-content/uploads/2017/06/Remington-J.-Peters.jpg','Remington J.', 'Peters','NaN','Navy','NaN','Special Warfare Operator 1st Class (SEAL)','5/28/2017','NaN','NaN', true